FROM murilopontes/ubuntu1804_yocto

COPY sdk/*.sh /opt
RUN /opt/poky-glibc-x86_64-core-image-minimal-aarch64-qemuarm64-toolchain-3.1.3.sh -y
RUN /opt/poky-glibc-x86_64-core-image-minimal-aarch64-toolchain-2.5.3.sh -y

